# CI de Nível 02 - Disparo agendado

# nome do nosso 'pipeline'
name: 'Execução Agendada'

# regras de disparo (gatinhos/triggers)
# gatilho de exec manual = workflow_dispatch

on:
  schedule:
    - cron: '0 6 * * 1'

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalacao do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalacao das dependencias
      - name: Instalando dependencias
        run: yarn

      # instalacao do Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Teste E2E
        run: yarn run e2e
